// The official role library data (supabase/data/official-roles.json) and its checks.

export type Team = 'townsfolk' | 'outsider' | 'minion' | 'demon';
export type Edition = 'tb' | 'bmr' | 'snv';

export interface OfficialRole {
  id: string;
  edition: Edition;
  team: Team;
  name: string;
  glyph: string;
  ability: string;
  reminders: string[];
}

/**
 * LIB-01: every character of the three base editions, excluding Travellers and
 * Fabled, by its standard script-tool ID.
 */
export const BASE_EDITION_IDS: Record<Edition, Record<Team, string[]>> = {
  tb: {
    townsfolk: ['washerwoman', 'librarian', 'investigator', 'chef', 'empath', 'fortuneteller', 'undertaker', 'monk', 'ravenkeeper', 'virgin', 'slayer', 'soldier', 'mayor'],
    outsider: ['butler', 'drunk', 'recluse', 'saint'],
    minion: ['poisoner', 'spy', 'scarletwoman', 'baron'],
    demon: ['imp'],
  },
  bmr: {
    townsfolk: ['grandmother', 'sailor', 'chambermaid', 'exorcist', 'innkeeper', 'gambler', 'gossip', 'courtier', 'professor', 'minstrel', 'tealady', 'pacifist', 'fool'],
    outsider: ['tinker', 'moonchild', 'goon', 'lunatic'],
    minion: ['godfather', 'devilsadvocate', 'assassin', 'mastermind'],
    demon: ['zombuul', 'pukka', 'shabaloth', 'po'],
  },
  snv: {
    townsfolk: ['clockmaker', 'dreamer', 'snakecharmer', 'mathematician', 'flowergirl', 'towncrier', 'oracle', 'savant', 'seamstress', 'philosopher', 'artist', 'juggler', 'sage'],
    outsider: ['mutant', 'sweetheart', 'barber', 'klutz'],
    minion: ['eviltwin', 'witch', 'cerenovus', 'pithag'],
    demon: ['fanggu', 'vigormortis', 'nodashii', 'vortox'],
  },
};

const HAN = /[一-鿿]/;

/** Validates the JSON and returns the roles; throws with every problem found. */
export function parseOfficialRoles(json: unknown): OfficialRole[] {
  if (!Array.isArray(json)) throw new Error('official roles must be an array');
  const problems: string[] = [];
  const roles = json as OfficialRole[];
  const seen = new Set<string>();
  for (const r of roles) {
    const where = `role ${r?.id ?? '?'}`;
    if (!r || typeof r.id !== 'string' || !/^[a-z0-9_-]+$/.test(r.id)) problems.push(`${where}: bad id`);
    if (seen.has(r.id)) problems.push(`${where}: duplicate`);
    seen.add(r.id);
    const expectedTeam = (Object.entries(BASE_EDITION_IDS[r.edition] ?? {}) as [Team, string[]][]).find(([, ids]) => ids.includes(r.id))?.[0];
    if (!expectedTeam) problems.push(`${where}: not a ${r.edition} character`);
    else if (r.team !== expectedTeam) problems.push(`${where}: team should be ${expectedTeam}`);
    if (typeof r.name !== 'string' || !HAN.test(r.name) || r.name.length > 20) problems.push(`${where}: needs a Chinese name`);
    if (typeof r.glyph !== 'string' || [...r.glyph].length !== 1) problems.push(`${where}: glyph must be one character`);
    if (typeof r.ability !== 'string' || !HAN.test(r.ability) || r.ability.length > 300) problems.push(`${where}: needs a Chinese ability`);
    if (!Array.isArray(r.reminders) || r.reminders.some((t) => typeof t !== 'string' || t.length > 8)) problems.push(`${where}: bad reminders`);
  }
  for (const [edition, teams] of Object.entries(BASE_EDITION_IDS)) {
    for (const ids of Object.values(teams)) for (const id of ids) if (!seen.has(id)) problems.push(`missing ${edition} character ${id}`);
  }
  if (problems.length) throw new Error(problems.join('\n'));
  return roles;
}

const q = (s: string) => `'${s.replaceAll("'", "''")}'`;

/** SQL that inserts or updates every official role. */
export function rolesUpsertSql(roles: OfficialRole[]): string {
  const rows = roles.map(
    (r) =>
      `  (${q(r.id)}, ${q(r.name)}, ${q(r.team)}, ${q(r.ability)}, ${q(r.glyph)}, array[${r.reminders.map(q).join(', ')}]::text[], ${q(r.edition)}, true)`,
  );
  return `-- Generated by tools/gen-roles-migration.ts from supabase/data/official-roles.json. Do not edit by hand.
-- LIB-01: the official role library (Trouble Brewing, Bad Moon Rising, Sects & Violets).
insert into public.roles (id, name, team, ability, glyph, reminders, edition, is_official) values
${rows.join(',\n')}
on conflict (id) do update set
  name = excluded.name, team = excluded.team, ability = excluded.ability, glyph = excluded.glyph,
  reminders = excluded.reminders, edition = excluded.edition, is_official = true;
`;
}
